In [1]:
!pwd

/app/backend/notebooks

In [2]:
import os
os.chdir(os.path.expanduser("../../backend/"))

In [3]:
print(os.getcwd())

/app/backend

In [4]:
from data_fetch import fetch_timestamp_data
from utils.constants import (
    BITCOIN_URL, 
    BITCOIN_REQUEST_PARAMS, 
    BITCOIN_RESPONSE_PARAMS, 
    BITCOIN_MODEL_PARAMS
)
from data_clean import clean_data_bitcoin
from model_preprocess import preprocess_data
from model_train import train_anomaly_model
from model_infer import infer_anomaly

In [5]:
# main
df = fetch_timestamp_data(BITCOIN_URL, BITCOIN_REQUEST_PARAMS, BITCOIN_RESPONSE_PARAMS)
df_clean = clean_data_bitcoin(df)
X_train, X_infer, train_df, infer_df, scaler = preprocess_data(df_clean, 'price')
model = train_anomaly_model(X_train, **BITCOIN_MODEL_PARAMS)
infer_df = infer_anomaly(BITCOIN_MODEL_PARAMS['save_path'], X_infer, infer_df)

In [6]:
infer_df.shape

(144, 5)

In [7]:
X_train, X_infer, train_df, infer_df, scaler = preprocess_data(df_clean, 'price')

In [8]:
infer_df = infer_anomaly(BITCOIN_MODEL_PARAMS['save_path'], X_infer, infer_df)

In [9]:
df.head()

                timestamp          price
0 2025-08-18 02:02:53.312  116457.326875
1 2025-08-18 03:01:30.899  115762.722944
2 2025-08-18 04:02:43.252  115355.153627
3 2025-08-18 05:03:07.777  115582.397650
4 2025-08-18 06:03:32.999  115677.243714

In [10]:
df.shape

(719, 2)

In [11]:
list(df_clean.columns)

['price', 'pct_change', 'rolling_mean', 'rolling_std']

In [12]:
df_clean.head(25)

                                 price  pct_change   rolling_mean  rolling_std
timestamp
2025-08-18 02:02:53.312  116457.326875    0.000000  115638.407551   403.841570
2025-08-18 03:01:30.899  115762.722944   -0.005964  115638.407551   403.841570
2025-08-18 04:02:43.252  115355.153627   -0.003521  115638.407551   403.841570
2025-08-18 05:03:07.777  115582.397650    0.001970  115638.407551   403.841570
2025-08-18 06:03:32.999  115677.243714    0.000821  115638.407551   403.841570
2025-08-18 07:03:21.362  115295.023270   -0.003304  115638.407551   403.841570
2025-08-18 08:03:48.982  115338.984774    0.000381  115638.407551   403.841570
2025-08-18 09:00:27.213  115197.405036   -0.001228  115458.418717   214.324745
2025-08-18 10:03:03.017  115074.780057   -0.001064  115360.141161   209.196395
2025-08-18 11:02:25.005  115124.873346    0.000435  115327.243978   227.423719
2025-08-18 12:00:38.558  115044.560049   -0.000698  115250.410035   217.490195
2025-08-18 13:02:19.735  115527.030931    0.004194  115228.951066   170.743780
2025-08-18 14:02:13.194  114995.269952   -0.004603  115186.129164   188.116076
2025-08-18 15:02:12.018  115648.194652    0.005678  115230.302003   254.560716
2025-08-18 16:03:21.565  116256.120457    0.005257  115381.547064   461.862671
2025-08-18 17:02:48.704  116083.857793   -0.001482  115525.701026   505.564795
2025-08-18 18:03:17.580  116717.500322    0.005458  115753.219165   636.519937
2025-08-18 19:03:07.996  116612.615917   -0.000899  115977.227146   621.296197
2025-08-18 20:02:47.066  116359.649189   -0.002169  116096.172612   600.081606
2025-08-18 21:02:34.740  116467.140709    0.000924  116306.439863   359.799029
2025-08-18 22:01:27.625  116713.437621    0.002115  116458.617430   240.480901
2025-08-18 23:02:51.292  116445.120547   -0.002299  116485.617443   224.001682
2025-08-19 00:06:58.562  116315.118790   -0.001116  116518.654728   163.849148
2025-08-19 01:02:57.300  116578.696111    0.002266  116498.825555   142.824067
2025-08-19 02:02:55.046  115840.822951   -0.006329  116388.569417   276.078658

In [13]:
infer_df

,price,pct_change,rolling_mean,rolling_std,anomaly
timestamp,,,,,
2025-09-11 03:01:16.610,113851.685394,-0.000646,113874.665877,119.137213,0
2025-09-11 04:01:45.613,114419.627585,0.004988,113988.066920,195.875222,0
2025-09-11 05:01:42.786,114167.933833,-0.002200,114028.442449,200.242957,0
2025-09-11 06:01:38.161,114273.229971,0.000922,114076.675656,214.320284,0
2025-09-11 07:02:56.015,114409.360504,0.001191,114135.138453,243.752742,0
...,...,...,...,...,...
2025-09-16 22:02:26.235,116776.271347,-0.000911,116504.499126,359.020648,0
2025-09-16 23:00:15.778,116872.967552,0.000828,116640.825829,269.526077,0
2025-09-17 00:02:23.026,116797.002060,-0.000650,116732.050763,167.975596,0
2025-09-17 01:02:47.493,116629.376314,-0.001435,116745.345021,152.909443,0
2025-09-17 01:38:30.000,116641.875657,0.000107,116772.101900,101.189949,0

In [14]:
train_df

                                 price  pct_change   rolling_mean  rolling_std
timestamp
2025-08-18 02:02:53.312  116457.326875    0.000000  115638.407551   403.841570
2025-08-18 03:01:30.899  115762.722944   -0.005964  115638.407551   403.841570
2025-08-18 04:02:43.252  115355.153627   -0.003521  115638.407551   403.841570
2025-08-18 05:03:07.777  115582.397650    0.001970  115638.407551   403.841570
2025-08-18 06:03:32.999  115677.243714    0.000821  115638.407551   403.841570
...                                ...         ...            ...          ...
2025-09-10 22:02:37.931  113885.305127    0.002284  113688.112609   174.346905
2025-09-10 23:02:16.643  113935.597521    0.000442  113692.633209   181.153516
2025-09-11 00:02:24.417  114000.120923    0.000566  113739.477001   214.348221
2025-09-11 01:02:22.679  113898.885155   -0.000888  113762.941591   222.562480
2025-09-11 02:01:57.331  113925.246733    0.000231  113810.545907   215.433179

[575 rows x 4 columns]

In [15]:
infer_df[infer_df['anomaly']==1].head().to_dict(orient='records')

[{'price': 114850.5440850557,
  'pct_change': -0.008132235242901298,
  'rolling_mean': 115760.13376476557,
  'rolling_std': 560.5760037741046,
  'anomaly': 1}]