In [1]:
import os
os.chdir(os.path.expanduser("../../backend/"))

In [2]:
print(os.getcwd())

/app/backend

In [3]:
from data_fetch import fetch_timestamp_data
from utils.constants import (
    BITCOIN_URL, 
    BITCOIN_REQUEST_PARAMS, 
    BITCOIN_RESPONSE_PARAMS, 
    BITCOIN_MODEL_PARAMS
)
from data_clean import clean_data_bitcoin
from model_preprocess import preprocess_data
from model_train import train_anomaly_model
from model_infer import infer_anomaly

In [4]:
# main
df = fetch_timestamp_data(BITCOIN_URL, BITCOIN_REQUEST_PARAMS, BITCOIN_RESPONSE_PARAMS)
df_clean = clean_data_bitcoin(df)
X_train, X_infer, train_df, infer_df, scaler = preprocess_data(df_clean, 'price')
model = train_anomaly_model(X_train, **BITCOIN_MODEL_PARAMS)
infer_df = infer_anomaly(BITCOIN_MODEL_PARAMS['save_path'], X_infer, infer_df)

In [5]:
X_train, X_infer, train_df, infer_df, scaler = preprocess_data(df_clean, 'price')

In [6]:
infer_df = infer_anomaly(BITCOIN_MODEL_PARAMS['save_path'], X_infer, infer_df)

In [7]:
df.head()

                timestamp          price
0 2025-08-17 21:02:23.419  117744.579390
1 2025-08-17 22:03:22.102  117792.213716
2 2025-08-17 23:01:54.800  118004.768689
3 2025-08-18 00:02:30.727  117519.356066
4 2025-08-18 01:03:14.591  117293.776627

In [8]:
df.shape

(719, 2)

In [8]:
list(df_clean.columns)

['price', 'pct_change', 'rolling_mean', 'rolling_std']

In [9]:
df_clean.head(25)

                                 price  pct_change   rolling_mean  rolling_std
timestamp
2025-08-17 21:02:23.419  117744.579390    0.000000  117224.963472   818.401417
2025-08-17 22:03:22.102  117792.213716    0.000405  117224.963472   818.401417
2025-08-17 23:01:54.800  118004.768689    0.001804  117224.963472   818.401417
2025-08-18 00:02:30.727  117519.356066   -0.004114  117224.963472   818.401417
2025-08-18 01:03:14.591  117293.776627   -0.001920  117224.963472   818.401417
2025-08-18 02:02:53.312  116457.326875   -0.007131  117224.963472   818.401417
2025-08-18 03:01:30.899  115762.722944   -0.005964  117224.963472   818.401417
2025-08-18 04:02:43.252  115355.153627   -0.003521  116883.616935  1035.153066
2025-08-18 05:03:07.777  115582.397650    0.001970  116567.928926  1048.750232
2025-08-18 06:03:32.999  115677.243714    0.000821  116235.425358   871.221708
2025-08-18 07:03:21.362  115295.023270   -0.003304  115917.663530   716.848839
2025-08-18 08:03:48.982  115338.984774    0.000381  115638.407551   403.841570
2025-08-18 09:00:27.213  115197.405036   -0.001228  115458.418717   214.324745
2025-08-18 10:03:03.017  115074.780057   -0.001064  115360.141161   209.196395
2025-08-18 11:02:25.005  115124.873346    0.000435  115327.243978   227.423719
2025-08-18 12:00:38.558  115044.560049   -0.000698  115250.410035   217.490195
2025-08-18 13:02:19.735  115527.030931    0.004194  115228.951066   170.743780
2025-08-18 14:02:13.194  114995.269952   -0.004603  115186.129164   188.116076
2025-08-18 15:02:12.018  115648.194652    0.005678  115230.302003   254.560716
2025-08-18 16:03:21.565  116256.120457    0.005257  115381.547064   461.862671
2025-08-18 17:02:48.704  116083.857793   -0.001482  115525.701026   505.564795
2025-08-18 18:03:17.580  116717.500322    0.005458  115753.219165   636.519937
2025-08-18 19:03:07.996  116612.615917   -0.000899  115977.227146   621.296197
2025-08-18 20:02:47.066  116359.649189   -0.002169  116096.172612   600.081606
2025-08-18 21:02:34.740  116467.140709    0.000924  116306.439863   359.799029

In [10]:
infer_df

,price,pct_change,rolling_mean,rolling_std,anomaly
timestamp,,,,,
2025-09-10 22:02:37.931,113885.305127,0.002284,113688.112609,174.346905,0
2025-09-10 23:02:16.643,113935.597521,0.000442,113692.633209,181.153516,0
2025-09-11 00:02:24.417,114000.120923,0.000566,113739.477001,214.348221,0
2025-09-11 01:02:22.679,113898.885155,-0.000888,113762.941591,222.562480,0
2025-09-11 02:01:57.331,113925.246733,0.000231,113810.545907,215.433179,0
...,...,...,...,...,...
2025-09-16 17:02:20.382,116158.427523,0.002068,115504.825457,394.920019,0
2025-09-16 18:00:28.989,116536.316506,0.003253,115667.449462,548.208606,0
2025-09-16 19:00:50.088,116454.577506,-0.000701,115825.849221,597.726451,0
2025-09-16 20:02:41.347,116804.438671,0.003004,116021.784450,668.100436,0
2025-09-16 20:27:01.000,116775.704891,-0.000246,116272.728609,547.775778,0

In [11]:
train_df

                                 price  pct_change   rolling_mean  rolling_std
timestamp
2025-08-08 04:00:23.065  116742.990459    0.000000  116697.206140    87.323094
2025-08-08 05:04:15.771  116766.055845    0.000198  116697.206140    87.323094
2025-08-08 06:04:35.218  116572.414322   -0.001658  116697.206140    87.323094
2025-08-08 07:08:51.305  116691.756959    0.001024  116697.206140    87.323094
2025-08-08 08:09:11.085  116800.737293    0.000934  116697.206140    87.323094
...                                ...         ...            ...          ...
2025-08-31 23:02:10.273  108867.780182   -0.001453  108991.916715    89.848984
2025-09-01 00:01:24.782  108253.360924   -0.005644  108892.521609   295.216022
2025-09-01 01:00:12.717  108320.528127    0.000620  108798.384723   360.669841
2025-09-01 02:02:30.453  108163.584894   -0.001449  108660.085512   395.494459
2025-09-01 03:02:20.902  107556.161684   -0.005616  108464.861361   550.964793

[577 rows x 4 columns]

In [12]:
infer_df[infer_df['anomaly']==1].head().to_dict(orient='records')

[{'price': 109681.77674236635,
  'pct_change': 0.014831419342523633,
  'rolling_mean': 108057.05843391102,
  'rolling_std': 766.9550012683967,
  'anomaly': 1},
 {'price': 108458.76073645355,
  'pct_change': -0.009382897068365703,
  'rolling_mean': 108654.11999882183,
  'rolling_std': 925.5036712078262,
  'anomaly': 1},
 {'price': 107541.65849979663,
  'pct_change': -0.011457852320686412,
  'rolling_mean': 108752.56230057144,
  'rolling_std': 567.0936305297345,
  'anomaly': 1},
 {'price': 108482.11328514619,
  'pct_change': 0.008745027726639876,
  'rolling_mean': 108712.08197044607,
  'rolling_std': 576.0608231167984,
  'anomaly': 1},
 {'price': 109229.01454657852,
  'pct_change': 0.006885017620085421,
  'rolling_mean': 108775.44984076709,
  'rolling_std': 608.9343137101341,
  'anomaly': 1}]